apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args: 
    - sleep
    - "1800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
